import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.scss";

const poppinsSans = Poppins({
  variable: "--font-poppins-sans",
  weight: ["300", "400", "600", "700"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${poppinsSans.variable} ${geistMono.variable}`}>
        <div id="__next">
          {children}
        </div>
      </body>
    </html>
  );
}
